### ISSUE TITLE
[Bug] Wacatac.H!ml in user32.dll

### ISSUE THREAD

**Issue by millionsofplayers** [SteamClientHomebrew/Millennium#91]
### Before Reporting

- [X] I found no existing issues matching my bug
- [X] My issue is not caused by the Millennium interface inside Steam (Themes, Plugins & Update Panel). If it is, make a issue report in [this repo](https://github.com/SteamClientHomebrew/Core).
- [X] My issue is not caused by a theme

### Describe the Bug

![image](https://github.com/user-attachments/assets/5e9dbcd5-6e6e-4bc2-8be4-008ffd1e4416)

### Expected Behavior

Not getting a virus popup from windows defender

### Steps To Reproduce

1. Launch steam
2. get this

### Operating System

Windows

### Anything else?

how do i uninstall millenium? not because of the popup, just because the only thing i use it for is themes

**Comment by shdwmtr** [comment]
Millennium just released a brand new version (about 10 minutes ago) so antiviruses haven't had enough time to properly authenticate Millennium, they usually go away after a few days. Windows Defender just sees a file you downloaded that isn't commonly downloaded (because it was just created) and sees it as potentially malicious.

You can uninstall with this guide: https://docs.steambrew.app/users/uninstalling
If you're concerned about the safety of your pc, you can join the discord server and ask around about your concerns :)

Happy patching!

**Comment by shdwmtr** [comment]
You can also check virus total, its just a false positive:
https://www.virustotal.com/gui/file/cdea5e9969ca9927ee31c15f33e04312b766f1ba3179ed95d776fcb3f7fe8d2c?nocache=1
